name: Scrape Products to Google Sheets

on:
  schedule:
    - cron: "0 */4 * * *"  # هر 4 ساعت (UTC)
  workflow_dispatch:       # اجرا به صورت دستی

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create service_account.json
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > service_account.json

      - name: Run scraper
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python scraper.py
